# Site settings
title: diginatu world
description: > # this means to ignore newlines until "baseurl:"
  プログラミングたのしい AIとか興味ある感じ
  電子機器とかも 現在D勉強中 最近はゆるく競プロやってる 
  [linux, TopCorder, AtCorder, Ubuntu, vim, C++, Dlang]
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://diginatu.github.io" # the base hostname & protocol for your site
twitter_username: diginatu
github_username: diginatu

# Build settings
markdown: kramdown
